#ifndef PACKETKEYS_H_INCLUDED
#define PACKETKEYS_H_INCLUDED

#define SERVER_IS_FULL_KEY 0

#define LOG_IN_KEY 1
#define LOG_IN_INVALID_USERNAME q
#define LOG_IN_INVALID_PASSWORD w

#define REGISTER_KEY 2

#endif // PACKETKEYS_H_INCLUDED
