#ifndef PACKETKEYS_H_INCLUDED
#define PACKETKEYS_H_INCLUDED

#define SERVER_IS_FULL_KEY 0

#define LOG_IN_KEY 1
#define LOG_IN_SUCCESS q
#define LOG_IN_INVALID_USERNAME w
#define LOG_IN_INVALID_PASSWORD e

#define REGISTER_KEY 2

#endif // PACKETKEYS_H_INCLUDED
